---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wisesayings
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wisesayings
    spec:
      containers:
      - name: wisesayings
        image: reselbob/wisesayings:v0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---